### ISSUE TITLE
Not able to add activities or devices

### ISSUE THREAD

**Issue by jahnkenneth** [jreenen/com.jreenen.homeyharmonyhub#49]
Homey 2.0.2. 
I am not able to add Avtivities or Devices. The app discovers my hub, bot When trying to add either Activities or Devices it times out...

**Comment by s1061429** [comment]
I have the same problem. My hub is discovered. But that is it. It ends with "Network request failed" or 30000ms timeout. Hope this will be solved quickly. I like the app very much, thank you for that! 

homeyVersion | "2.0.2"
-- | --

**Comment by jreenen** [comment]
@jahnkenneth @s1061429 I am currently investigating this issue. Seems to be happening on the latest Logitech Harmony Hub firmware v4.15.250 can you confirm you are on this version?

**Comment by jahnkenneth** [comment]
Yes, i am on v4.15.250

**Comment by Jesa-a1** [comment]
I am on v4.1.5.250 and Homey 1.5.13

I cannot start add devices or devices. It sees the hub, that's it.

And I cannot start or stop activity. Or control devices.

I see that this Harmony version now have the XMPP setting for local API. I tried to enable it. Before enabling XMPP (yesterday evening) my harmony devices was reported offline in Homey. After enabling the devices is seemingly online again. But I cannot control them or activities.

**Comment by TheBluProject** [comment]
Same here, update was pushed automatically, tried re-installing the app, it detects the hub but it does not see / add devices or activities.

https://community.logitech.com/s/question/0D55A00008OsX3CSAV

**Comment by s1061429** [comment]
Yes, I am on 4.15.250

**Comment by jreenen** [comment]
Have found the issue, the good news is that it seems fixable but it will take me some time (around 2 days) to code the fix. Will keep you updated on this.

**Comment by jahnkenneth** [comment]
Good to hear! Keep up the good work!
I really appreciate your work, so I made a small donation. :-)

**Comment by vladivdv** [comment]
we wait for correction what works from developers. Please correct, at me is them in the house of 6 pieces... and all were in HOMEY, help

**Comment by jreenen** [comment]
@vladivdv working on a solution, my expectation is that the coding will be done today, after that, I will perform some testing and publish an updated version to the store. After that, we need to wait for Athom's approval.

**Comment by jreenen** [comment]
While working on the fix I also detected that since the latest Logitech Harmony Hub firmware they changed the unique id of the hub. I have a version fully working now that would require deletion of all devices and activities + a repair of those devices. At the moment I am looking into a way to prevent this, although this would take a bit longer for the fix to hit the store, I don't want to confront everyone with having to re-do all their flows so I think it's worth the wait.

I expect to publish a new version late tomorrow or early on the day after tomorrow. After that, we need to wait for Athom's approval.

Sorry for the inconvenience,

Jeroen

**Comment by jreenen** [comment]
I am currently testing the version that is available for CLI install on https://github.com/jreenen/com.jreenen.homeyharmonyhub/tree/fix/latest_hub_firmware

Currently, there is one known issue: if you pull the plug from your hub the app doesn’t detect it. I want to fix it but I might publish this version with the known issue if I can’t fix it today.

**Comment by AlbertDijksma** [comment]
Hi Jeroen,
Everything works again.
Now I can operate my Kalox curtains again via the harmony hub.
I had to reconfigure the devices and flows.
Super thanks that everything is fixed so quickly.
Greetings
Albert

**Comment by lukefairbank** [comment]
Thanks for all your work on this. I have installed the beta version. From the link above and it's still not working. I can add devices but get the error "cannot read property 'ip' of undefined" when trying to send commands

**Comment by jreenen** [comment]
@lukefairbank could you try to power cycle the hub? After that restart the app. Do you experience the same problems?

**Comment by jahnkenneth** [comment]
The same happened to me, but it resolved itself after restarting the app. 😀

**Comment by tranceblast** [comment]
> @lukefairbank could you try to power cycle the hub? After that restart the app. Do you experience the same problems?

Thanks! This worked for me :)

**Comment by tranceblast** [comment]
Thank you @jreenen this worked for me :)

**Comment by lukefairbank** [comment]
All good now, thanks

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jreenen** [comment]
@jahnkenneth, @vladivdv does v2.0.2 fixes the issues you where experiencing?

**Comment by jahnkenneth** [comment]
Yes! Thank you very much!

**Comment by s1061429** [comment]
Thanks you for fixing the problem. Works perfect again!

**Comment by zeppie** [comment]
Thx!!

**Comment by jreenen** [comment]
Since most users are reporting this issue is fixed I am going to close this one. If you still experience issues feel free to create a new issue.

**Comment by maaikekaasenbrood** [comment]
My issues have not been fixed by the update :(

**Comment by MrBlue90** [comment]
I'm unfortunately still experiencing this issue.
After adding the activities or devices, I get a timeout and the app crashes.

I've ran the diagnostics report: dd516d22-5395-4a07-878f-ad1216820f32
Homey: 2.1.2
App: 2.0.2
Hub: 4.15.250

Could you please have a look at this?
Much appreciated!
